language: ruby
cache: bundler
rvm:
  - 2.3.1

before_script: gem install awesome_bot

script: awesome_bot _posts/*.md  support/**/*.md  support/*.md contact/*.md  pulse/*.md --allow-dupe --allow-redirect --skip-save-results
notifications:
  email: false
