# Site settings
title: Subnero
description: > # this means to ignore newlines until "baseurl:"
  The future of underwater wireless.
baseurl: "/website/" # the subpath of your site, e.g. /blog/
url: "http://subnero1.github.io/" # the base hostname & protocol for your site
twitter_username: subnero
github_username:  subnero1

# Build settings
markdown: kramdown
encoding:    UTF-8
highlighter: rouge

