# Site settings
title: Subnero
description: "Subnero designs and manufactures advanced underwater acoustic modems and networking solutions, enabling reliable wireless communications for ocean monitoring, subsea IoT and marine robotics."
keywords: "underwater communication, acoustic modems, underwater acoustic modem, subsea wireless, marine data communication, underwater telemetry, underwater networking, underwater sensor networks, subsea IoT, ocean technology"
url: "http://subnero1.github.io/"
twitter_username: subnero
github_username:  subnero1
default_image: images/pulse-thumbnail-default.jpg

collections:
  - faq

# Build settings
markdown: kramdown
encoding:    UTF-8
highlighter: rouge

# Google Analytics
google_analytics: UA—130948711-1
