- name: All Products
  id: tab-one
  input_id: all-products
  panel_id: panel-one
- name: L5L series
  id: tab-two
  input_id: L5Lseries
  panel_id: panel-two
- name: M25M series
  id: tab-three
  input_id: M25Mseries
  panel_id: panel-three
- name: Optional accessories
  id: tab-four
  input_id: optacc
  panel_id: panel-four