- name: All Products
  id: tab-one
  input_id: all-products
  panel_id: panel-one
- name: S40H series
  id: tab-two
  input_id: S40Hseries
  panel_id: panel-two
- name: L12L series
  id: tab-three
  input_id: L12Lseries
  panel_id: panel-three
- name: M25M series
  id: tab-four
  input_id: M25Mseries
  panel_id: panel-four
- name: Optional accessories
  id: tab-five
  input_id: Accessories
  panel_id: panel-five