name: Broken link check
on:
  schedule:
    - cron:  '0 2 * * 1,5'
  workflow_dispatch:

jobs:
  markdown-link-check:
    name: Check markdown files for broken links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate link check config with internal link replacement patterns
      run: |
        jq --arg ws "/github/workspace" '. + {
            "replacementPatterns": [
              {"pattern": "^(/[^#?]+/)$",   "replacement": ("file://" + $ws + "$1")},
              {"pattern": "^(/[^#?.]+)$",   "replacement": ("file://" + $ws + "$1.md")},
              {"pattern": "^(/[^#?]+\\.[A-Za-z0-9]+)$",   "replacement": ("file://" + $ws + "$1")}
            ]
          }' \
          .github/workflows/markdown.links.config.json > "$GITHUB_WORKSPACE/.github/workflows/mlc.config.generated.json"
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      id: checker
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc.config.generated.json'
